services:
  britive-broker:
    build: .
    image: britive-broker:latest
    container_name: britive-broker
    hostname: britive-broker-prod
    environment:
      # Required configuration
      - TENANT_SUBDOMAIN=${TENANT_SUBDOMAIN}
      - AUTHENTICATION_TOKEN=${AUTHENTICATION_TOKEN}
      # Optional Java configuration
      - JAVA_OPTS=-Xmx512m -Xms256m
      # CloudWatch logging configuration
      - AWS_REGION=${AWS_REGION:-us-east-1}
      - CLOUDWATCH_LOG_GROUP=${CLOUDWATCH_LOG_GROUP:-/aws/docker/britive-broker}
      - CLOUDWATCH_LOG_STREAM=${CLOUDWATCH_LOG_STREAM:-britive-broker-prod}
      - LOG_TO_STDOUT=${LOG_TO_STDOUT:-true}
    # Logging configuration - choose one of the following options:
    # Option 1: CloudWatch Logs (requires AWS credentials and awslogs driver)
    logging:
      driver: awslogs
      options:
        awslogs-region: ${AWS_REGION:-us-east-1}
        awslogs-group: ${CLOUDWATCH_LOG_GROUP:-/aws/docker/britive-broker}
        awslogs-stream: ${CLOUDWATCH_LOG_STREAM:-britive-broker-prod}
        awslogs-create-group: "true"
    # Option 2: JSON file logging (uncomment to use instead of CloudWatch)
    # logging:
    #   driver: json-file
    #   options:
    #     max-size: "100m"
    #     max-file: "5"
    #     labels: "service=britive-broker"
    volumes:
      # Persist logs and cache data
      - britive-logs:/app/logs
      - britive-cache:/app/cache
    # Uncomment and adjust if your broker needs specific port exposure
    # ports:
    #   - "8080:8080"
    restart: unless-stopped

volumes:
  britive-logs:
    driver: local
  britive-cache:
    driver: local