services:
  britive-broker:
    build: .
    image: britive-broker:latest
    environment:
      # Required configuration
      - TENANT_SUBDOMAIN=${TENANT_SUBDOMAIN}
      - AUTHENTICATION_TOKEN=${AUTHENTICATION_TOKEN}
      # Optional Java configuration
      - JAVA_OPTS=${JAVA_OPTS:--Xmx512m -Xms256m}
      - LOG_TO_STDOUT=true
    volumes:
      # Persist logs and cache data
      - britive-logs:/app/logs
      - britive-cache:/app/cache
      # Optional: Mount logs to host for easy access
      - ./logs:/app/logs
      # Mount SSH keys directory
      - ./ssh-keys:/opt/britive-broker/.ssh:ro
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"
        labels: "service=britive-broker"
    restart: unless-stopped

volumes:
  britive-logs:
    driver: local
  britive-cache:
    driver: local